POST https://fcm.googleapis.com/fcm/send
Content-Type: application/json
Authorization: key={{ server_key }}

{
  "to": "fw2bEt-3S4Oi9LCDmEPGfn:APA91bFnbQFNX1kNGHl5ICEj4_VUmLjJScuhQo1VlnXFzVG3AZfqCCMc08W3aGg2C3gB5-7eqz-umxokt-M3Gu6C2NWbaYW9U5kf0Ari_Nbj0ts084giakohxORft9o9rKHjPa-gF9jT",
  "data": {
    "message": "This is a Firebase Cloud Messaging Topic Message!"
  },
  "notification": {
    "title": "FCM Message",
    "body": "This is a Firebase Cloud Messaging Topic Message!"
  }
}

###
